<a href="https://colab.research.google.com/github/Suhanii054/DEEP-LEARNING/blob/main/DL_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction of PyTorch Tensors and Basic Operations.
a) To understand PyTorch tensors, their initialization methods, and data types.
b) To perform tensor operations such as arithmetic, broadcasting, indexing, and
reshaping.
c) To explore automatic differentiation using PyTorch’s Autograd system.


In [ ]:
#1a)
import torch

# Creating tensors
a = torch.tensor([1, 2, 3])              # Integer tensor
b = torch.tensor([1.5, 2.5, 3.5])         # Float tensor

# Creating tensors with predefined shapes
c = torch.zeros((2, 3))                   # 2x3 tensor of zeros
d = torch.ones((3, 2))                    # 3x2 tensor of ones
e = torch.rand((2, 2))                    # Random values between 0 and 1

# Checking data types
print(a.dtype)
print(b.dtype)

# Changing data type
f = a.float()
print(f.dtype)


torch.int64
torch.float32
torch.float32


In [ ]:
#1b)

# Arithmetic operations
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print(x + y)   # Addition
print(x * y)   # Multiplication
print(x - y)   # Subtraction

# Broadcasting
m = torch.tensor([[1], [2], [3]])   # 3x1
n = torch.tensor([10, 20, 30])       # 1x3

print(m + n)   # Broadcasting happens automatically

# Indexing
z = torch.tensor([[1, 2], [3, 4]])
print(z[0])        # First row
print(z[1][1])     # Element 4

# Reshaping
r = torch.arange(6)
r = r.reshape(2, 3)
print(r)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([-3, -3, -3])
tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
tensor([1, 2])
tensor(4)
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
#1c)
# Tensor with gradient tracking
x = torch.tensor(2.0, requires_grad=True)

# Simple computation
y = x ** 2 + 3*x + 1

# Backpropagation
y.backward()

print("Value of y:", y.item())
print("Gradient dy/dx:", x.grad)


Value of y: 11.0
Gradient dy/dx: tensor(7.)


# **2) Perform all linear algebra operation with Tensorflow.**

In [ ]:
import tensorflow as tf

# Creating tensors
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Matrix addition
print("Addition:\n", A + B)

# Matrix multiplication
print("Multiplication:\n", tf.matmul(A, B))

# Transpose
print("Transpose:\n", tf.transpose(A))

# Determinant
print("Determinant:", tf.linalg.det(A))

# Inverse
print("Inverse:\n", tf.linalg.inv(A))

# Eigenvalues
eigen_vals = tf.linalg.eig(A)
print("Eigenvalues:", eigen_vals[0])


Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Multiplication:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Transpose:
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
Determinant: tf.Tensor(-2.0, shape=(), dtype=float32)
Inverse:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
Eigenvalues: tf.Tensor([-0.37228122+0.j  5.372281  +0.j], shape=(2,), dtype=complex64)


# Write a program to implement AND OR gates using Perceptron.

In [ ]:
import numpy as np

# Input data
X = np.array([[0,0], [0,1], [1,0], [1,1]])

# AND Gate
y_and = np.array([0, 0, 0, 1])

# OR Gate
y_or = np.array([0, 1, 1, 1])

# Perceptron function
def perceptron(X, y, lr=0.1, epochs=10):
    weights = np.zeros(X.shape[1])
    bias = 0

    for _ in range(epochs):
        for i in range(len(X)):
            linear_output = np.dot(X[i], weights) + bias
            y_pred = 1 if linear_output >= 0 else 0

            error = y[i] - y_pred
            weights += lr * error * X[i]
            bias += lr * error

    return weights, bias

# Training AND gate
w_and, b_and = perceptron(X, y_and)
print("AND gate weights:", w_and, "bias:", b_and)

# Training OR gate
w_or, b_or = perceptron(X, y_or)
print("OR gate weights:", w_or, "bias:", b_or)


AND gate weights: [0.2 0.1] bias: -0.20000000000000004
OR gate weights: [0.1 0.1] bias: -0.1


# Implementation of XOR Problem using PyTorch Neural Network.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# XOR dataset
X = torch.tensor([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])
y = torch.tensor([[0.], [1.], [1.], [0.]])

# Neural Network model
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        self.hidden = nn.Linear(2, 4)
        self.output = nn.Linear(4, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        x = torch.sigmoid(self.output(x))
        return x

model = XORNet()

# Loss function (ERROR)
criterion = nn.MSELoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
epochs = 2000
for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(X)
    loss = criterion(y_pred, y)
    loss.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# Final prediction
print("\nFinal Predictions:")
print(model(X).detach())


Epoch 0, Loss: 0.25348514318466187
Epoch 400, Loss: 0.10351380705833435
Epoch 800, Loss: 0.025205574929714203
Epoch 1200, Loss: 0.011101115494966507
Epoch 1600, Loss: 0.006679925136268139

Final Predictions:
tensor([[0.0834],
        [0.9514],
        [0.9514],
        [0.0834]])


# Implement Simple below Neural Network to solve regression problem.

In [ ]:
# Import required libraries
import torch
import torch.nn as nn
import torch.optim as optim

# -----------------------------
# Step 1: Create sample dataset
# -----------------------------
# Input has 2 features (x1, x2)
X = torch.tensor([
    [1.0, 2.0],
    [2.0, 1.0],
    [3.0, 4.0],
    [4.0, 3.0]
])

# Target output (regression values)
y = torch.tensor([
    [5.0],
    [5.0],
    [11.0],
    [11.0]
])

# -----------------------------
# Step 2: Define Neural Network
# -----------------------------
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()

        # Input layer (2 inputs) → Hidden layer (2 neurons)
        self.hidden = nn.Linear(2, 2)

        # Hidden layer (2 neurons) → Output layer (1 neuron)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        # Apply activation function to hidden layer
        z1 = torch.relu(self.hidden(x))

        # Output layer (no activation for regression)
        z2 = self.output(z1)
        return z2

# Create model
model = SimpleNN()

# -----------------------------
# Step 3: Define Loss and Optimizer
# -----------------------------

# Mean Squared Error Loss (ERROR)
criterion = nn.MSELoss()

# Optimizer (Gradient Descent)
optimizer = optim.SGD(model.parameters(), lr=0.01)

# -----------------------------
# Step 4: Training the Network
# -----------------------------
epochs = 1000

for epoch in range(epochs):
    # Clear previous gradients
    optimizer.zero_grad()

    # Forward pass
    predictions = model(X)

    # Calculate MSE loss
    loss = criterion(predictions, y)

    # Backpropagation
    loss.backward()

    # Update weights
    optimizer.step()

    # Print loss every 200 epochs
    if epoch % 200 == 0:
        print(f"Epoch {epoch}, MSE Loss: {loss.item():.6f}")

# -----------------------------
# Step 5: Final Output
# -----------------------------
print("\nFinal Predictions:")
print(model(X).detach())

# Manual MSE calculation (for clarity)
manual_mse = torch.mean((model(X) - y) ** 2)
print("\nManual MSE:", manual_mse.item())


Epoch 0, MSE Loss: 96.776199
Epoch 200, MSE Loss: 0.023778
Epoch 400, MSE Loss: 0.001120
Epoch 600, MSE Loss: 0.000049
Epoch 800, MSE Loss: 0.000002

Final Predictions:
tensor([[ 5.0004],
        [ 5.0004],
        [10.9998],
        [10.9998]])

Manual MSE: 9.018867785925977e-08
